#!/usr/bin/python3

def raise_exception():
    raise ValueError('This exception was raise intentionally')




if __name__=='__main__':
    raise_exception_msg()

